### ISSUE TITLE
Doesn't configure with cmake 3.21 and hipcc

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/rocBLAS#1196] opened 2021-08-04 16:49 UTC
Somehow using cmake 3.21 and CXX=hipcc cmake errors out:

```
-- The CXX compiler identification is ROCMClang 4.2.0

...

CMake Error at library/CMakeLists.txt:135 (elseif):
  given arguments:

    "HIP_RUNTIME" "MATCHES" "*cuda*"

  Regular expression "*cuda*" cannot compile
```

This bug has been there for a long time, but apparently it was never triggered cause HIP_RUNTIME is always rocclr, and the regex only gets compiled in a branch that's never hit.

Except with cmake 3.21...

Apparently if you set CXX=hipcc cmake recognizes the compiler as ROCMClang, and then CMAKE_CXX_COMPILER is set to the underlying clang, which makes this branch never execute:

```
if( CMAKE_CXX_COMPILER MATCHES ".*/hipcc$" )
  find_package( hip REQUIRED CONFIG PATHS ${ROCM_PATH} /opt/rocm )
endif( )
```

I feel the hip support in cmake 3.21 is very broken... (similar issues in rocfft).

Should this branch now check for `CMAKE_CXX_COMPILER_ID STREQUAL ROCMClang`?

**Comment by haampie** [comment] 2021-08-04 16:58
Oh, has this been fixed in rocm 4.3.0?

**Comment by TorreZuk** [comment] 2021-08-04 17:12
The regex has been fixed but yes we don't want it to even go to that branch in the code.  
@cgmb has suggested a workaround 
set(__skip_rocmclang ON)
until the issue is addressed in cmake: https://gitlab.kitware.com/cmake/cmake/-/issues/22460

**Comment by haampie** [comment] 2021-08-04 17:13
So you're not supposed to use find_package(hip) anymore after cmake 3.21.x fixes their issues?

**Comment by TorreZuk** [comment] 2021-08-04 17:45
> library/CMakeLists.txt:135 (elseif):
The cuda regex branch we don't expect it to go into, find_package(hip) should be executed as before.    The cmake issue is for compiler features.  Depending on how things change in CMake we will have to adapt code like CMAKE_CXX_COMPILER_ID matches "Clang" which has already changed from 4.3 release.

**Comment by littlewu2508** [comment] 2021-08-05 08:23
I manually skip this issue by replacing `*cuda*` with `cuda`, however I encountered the following errors:

```
CMake Error at library/CMakeLists.txt:20 (_target_compile_features):
  _target_compile_features The compiler feature "cxx_static_assert" is not
  known to CXX compiler

  "ROCMClang"

  version .
Call Stack (most recent call first):
  clients/benchmarks/CMakeLists.txt:28 (target_compile_features)
```

**Comment by littlewu2508** [comment] 2021-08-05 08:25
And if I set `-DBUILD_CLIENTS_TESTS=OFF` and `-DBUILD_CLIENTS_BENCHMARKS=OFF` to disable building rocblas-test and rocblas-benchmark, I encounter cmake generation error: 

```
-- Configuring done
CMake Error at library/src/CMakeLists.txt:335 (add_library):
  Target "rocblas" links to target "hip::device" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by littlewu2508** [comment] 2021-08-05 09:57
> The regex has been fixed but yes we don't want it to even go to that branch in the code.
> @cgmb has suggested a workaround
> set(__skip_rocmclang ON)
> until the issue is addressed in cmake: https://gitlab.kitware.com/cmake/cmake/-/issues/22460

Oh that really helps. Thanks!

**Comment by TorreZuk** [comment] 2021-08-05 14:50
Yes @littlewu2508 the find_package(hip) will provide all the required hip:: dependencies.   
We can leave this ticket open until the cmake issue is sorted out which may require additional changes on our side, but for now use either an older CMake or set(__skip_rocmclang ON).

**Comment by TorreZuk** [comment] 2021-09-24 23:21
cmake 3.21.3 should fix this issue so closing.   https://gitlab.kitware.com/cmake/cmake/-/commits/v3.21.3/
If this doesn't suffice either reopen this or make a new issue.  Thanks for reporting the problem.

**Closed by TorreZuk** 2021-09-24 23:21 UTC

**Comment by haampie** [comment] 2021-09-24 23:22
Yup, I've created a PR to fix this in spack, thanks for confirming.
