### ISSUE TITLE
rocBLAS cannot be used without a HIP compiler

### ISSUE THREAD

**Issue by nstomlinson** [ROCmSoftwarePlatform/rocBLAS#155] opened 2017-10-30 11:54 UTC
### What is the expected behavior
When using rocBLAS as a library, it should not be necessary to build the application using a HIP compiler.

### What actually happens
Because rocBLAS uses HIP features in its public API, it's necessary to build with a compiler that supports HIP. This could be solved by wrapping, as part of rocBLAS's API, the parts of the HIP API that are necessary to use rocBLAS.

**Comment by gstoner** [comment] 2017-10-30 12:43
It was designed to work with HIP,  what language runtime are you trying to link it with

**Comment by gstoner** [comment] 2017-10-30 12:45
From the front page "A BLAS implementation on top of AMD's Radeon Open Compute ROCm runtime and toolchains. rocBLAS is implemented in the HIP programming language and optimized for AMD's latest discrete GPUs."

**Comment by jszuppe** [comment] 2017-10-30 14:27
Are you talking about this https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/143 issue?

**Comment by nstomlinson** [comment] 2017-10-30 14:34
jszuppe: Your issue is related, yes.

What I'm saying is that it's probably useful to be able to *use* rocBLAS from, say a C++ program without having to use a HIP compiler. Imagine the following use case:
 - I'm developing a C++ program, and I need a BLAS library.
 - I want to use rocBLAS so I can take advantage of the GPU.
 - But I don't want to have to build my entire program with `hcc` just to use rocBLAS.
In CUDA land, it's possible to use cuBLAS from a vanilla C/C++ compiler.

**Comment by jszuppe** [comment] 2017-10-30 14:49
Why do you need to compile your code using `hcc`? 

After you compile rocBLAS with `hcc`, you should only have to  add include path to dir with rocRAND header and to HIP headers (and to CUDA headers if on CUDA platform), link against rocBLAS library and against HIP/CUDA (`"-L${HIP_ROOT_DIR}/lib -lhip_hcc -Wl,-rpath,${HIP_ROOT_DIR}/lib"`).

**Comment by kknox** [comment] 2017-10-30 14:55
I understand your issue, and I'm going to close this as a duplicate of #143.  This is a problem in our cmake infrastructure (both hip and rocblas), and I'm working on a solution.  I've had a couple of false starts, but I think I've got something workable in my fork of our rocFFT library.  In rocFFT, I've demonstrated I can build the rocFFT samples with a separate compiler than the main library.  When I get this code merged in (still need a few cleanups), I'll start porting this over to rocblas.

**Comment by nstomlinson** [comment] 2017-10-30 14:57
It's not quite a duplicate of #143 because it's not *just* a cmake issue. rocBLAS includes HIP headers that use things like `__device__`.

**Comment by kknox** [comment] 2017-10-30 15:00
OK, that's a fair point to track separately.  Reopening.

**Comment by nstomlinson** [comment] 2017-10-30 15:48
`rocblas-types.h` includes `hip_vector_types.h`, yes. Even if that header is put on the include path, it won't work because neither `__HIP_PLATFORM_HCC__` nor `__HIP_PLATFORM_NVCC__` would be defined.

`rocblas-auxiliary.h` includes `hip_runtime_api.h`

Uh. OK. I haven't found a use of `__device__`. But they still use HIP specific things.

**Comment by nstomlinson** [comment] 2017-10-30 15:51
`rocblas-types.h` also depends on a definition of `float2` and friends, which wouldn't be available in vanilla C or C++.

**Comment by tingxingdong** [comment] 2017-10-30 15:52
Thank you for pointing out:

**Comment by tingxingdong** [comment] 2017-10-30 16:06
Sorry I just carelessly close it and reopen now. 
1) the  "<hip/hip_runtime_api.h>" should be removed from rocblas-auxiliary.h. It does not make any sense here. I think we may carelessly put it here. 

2) Yes, float2 or float3 are not standard C++ types.  It is true for CUDA and HIP.

**Comment by nstomlinson** [comment] 2017-10-30 16:54
I think the reason `hip/hip_runtime_api.h` is in `rocblas-auxiliary.h` is to get access to `hipStream_t`.

**Comment by tingxingdong** [comment] 2017-10-30 18:30
add "CPPFLAGS += $(shell $(HIP_PATH)/bin/hipconfig --cpp_config)" to your makefile

**Comment by tingxingdong** [comment] 2017-10-30 19:04
I make an example and test the example code on the latest rocm 1.6.4. It passed with the g++ compiler:  see here

https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Example-C--code-calling-rocBLAS-routine-with-hipcc-and-or-gnu-compiler

$ g++ --version 
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by tingxingdong** [comment] 2017-11-01 21:24
If you are able to build, then I will close this issue.

**Comment by nstomlinson** [comment] 2017-11-01 22:33
Ah. I see. That should work. Thanks.

**Closed** 2017-11-03 22:50 UTC
