### ISSUE TITLE
how to resolve CMake error

### ISSUE THREAD

**Issue by ye-luo** [ROCmSoftwarePlatform/rocBLAS#1226] opened 2021-11-18 05:13 UTC
Trying to build rocblas from rocm-4.5.0 tag.

### What is the expected behavior
Get through CMake step.

### What actually happens
Got error 
```

*******************************************************************************
*----------------------------------- ERROR -----------------------------------*
* The variable 'CMAKE_CXX_FLAGS' should only be set by the cmake toolchain,
* either by calling 'cmake -DCMAKE_CXX_FLAGS=" -D__HIP_HCC_COMPAT_MODE__=1 -std=c++14"' or
* set in a toolchain file and added with
* 'cmake -DCMAKE_TOOLCHAIN_FILE=<toolchain-file>'.
*-----------------------------------------------------------------------------*
*******************************************************************************

CMake Warning at /opt/rocm/share/rocm/cmake/ROCMChecks.cmake:41 (message):
  The toolchain variable 'CMAKE_CXX_FLAGS' is modified in the CMakeLists.txt.
Call Stack (most recent call first):
  build/release/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/CMakeLists.txt:9223372036854775807 (rocm_check_toolchain_var)
  build/release/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/CMakeLists.txt:24 (set)


-- hip::amdhip64 is SHARED_LIBRARY
-- Using AMDGPU_TARGETS: gfx906
-- Tensile script: /home/yeluo/opt/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /home/yeluo/opt/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary;--new-client-only;--no-legacy-components;--merge-files;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--library-format=msgpack;--architecture=gfx906;/home/yeluo/opt/rocBLAS/library/src/blas3/Tensile/Logic/asm_full;/home/yeluo/opt/rocBLAS/build/release/Tensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /home/yeluo/opt/rocBLAS/build/release/Tensile/library/TensileManifest.txt
'/home/yeluo/opt/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary' '--new-client-only' '--no-legacy-components' '--merge-files' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--library-format=msgpack' '--architecture=gfx906' '/home/yeluo/opt/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/home/yeluo/opt/rocBLAS/build/release/Tensile' 'HIP' '--generate-manifest-and-exit'
Traceback (most recent call last):
  File "/home/yeluo/opt/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 25, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile.TensileCreateLibrary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yeluo/opt/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 32, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile.TensileCreateLibrary'
CMake Error at build/release/virtualenv/cmake/TensileConfig.cmake:236 (message):
  Error creating Tensile library: 1
Call Stack (most recent call first):
  library/src/CMakeLists.txt:68 (TensileCreateLibraryFiles)


-- Configuring incomplete, errors occurred!
See also "/home/yeluo/opt/rocBLAS/build/release/CMakeFiles/CMakeOutput.log".
```

### How to reproduce
```
./install.sh -d -a gfx906
```

### Environment
ubuntu 20.04.

| Software | version |
|-----|-----|
| ROCm | v4.5 |

**Comment by amcamd** [comment] 2021-11-19 00:36
Can you please check how much memory you have on your machine with the command:

free -h

It is recommended that you have 64 GB to build rocBLAS.

Can you also confirm that you have a gfx906 machine with the command:

rocm_agent_enumerator

Below is output on my machine:

> free -h
              total        used        free      shared  buff/cache   available
Mem:           62Gi       7.4Gi        32Gi        18Mi        22Gi        54Gi
Swap:          63Gi          0B        63Gi
> rocm_agent_enumerator
gfx000
gfx906




I have just built on the above machine with commands below. Please note -agfx906:xnack-  in place of -a gfx906:


> git clone -b release/rocm-rel-4.5  git@github.com:ROCmSoftwarePlatform/rocBLAS.git

> cd rocBLAS

> VERBOSE=1 ./install.sh -d -agfx906:xnack- 2>&1 | tee install.out


A snip from output is:

- ROCclr at /opt/rocm/lib/cmake/rocclr
-- hip::amdhip64 is SHARED_LIBRARY
-- Using AMDGPU_TARGETS: gfx906:xnack-
-- Tensile script: /home/achapman/repos/issue_1226/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /home/achapman/repos/issue_1226/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary;--new-client-only;--no-legacy-components;--merge-files;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--library-format=msgpack;--architecture=gfx906:xnack-;/home/achapman/repos/issue_1226/rocBLAS/library/src/blas3/Tensile/Logic/asm_full;/home/achapman/repos/issue_1226/rocBLAS/build/release/Tensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /home/achapman/repos/issue_1226/rocBLAS/build/release/Tensile/library/TensileManifest.txt
'/home/achapman/repos/issue_1226/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary' '--new-client-only' '--no-legacy-components' '--merge-files' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--library-format=msgpack' '--architecture=gfx906:xnack-' '/home/achapman/repos/issue_1226/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/home/achapman/repos/issue_1226/rocBLAS/build/release/Ten              cap gfx000 gfx803 gfx900 gfx906 gfx908 gfx90a gfx1010 gfx1011 gfx1012 gfx1030
   HasMFMA_bf16_1k      0      0      0      0      0      1       0       0       0       0
        HasAddLshl      0      0      1      1      1      1       1       1       1       1
      HasAtomicAdd      0      0      0      0      1      1       0       0       0       0
   HasCodeObjectV3      0      1      1      1      1      1       1       1       1       1
    HasDirectToLds      0      1      1      1      1      1       1       1       1       1
     HasExplicitCO      0      0      1      1      1      1       1       1       1       1
     HasExplicitNC      0      0      0      0      0      0       1       1       1       1
         HasLshlOr      0      0      1      1      1      1       1       1       1       1
           HasMFMA      0      0      0      0      1      1       0       0       0       0
         HasSMulHi      0      0      1      1      1      1       1       1       1       1
        MaxLgkmcnt      1      1      1      1      1      1       1       1       1       1
          MaxVmcnt      0      1      1      1      1      1       1       1       1       1
      SupportedISA      0      1      1      1      1      1       1       1       1       1
   SupportedSource      1      1      1      1      1      1       1       1       1       1
    v_dot2_f32_f16      0      0      0      1      1      1       0       1       1       1
   v_dot2c_f32_f16      0      0      0      0      1      1       0       1       1       1
         v_fma_f16      0      0      1      1      1      1       1       1       1       1
        v_fmac_f16      0      0      0      0      0      0       0       0       0       0
         v_mac_f16      0      1      1      1      1      1       0       0       0       0
      v_pk_fma_f16      0      0      1      1      1      1       1       1       1       1
     v_pk_fmac_f16      0      0      0      0      0      0       0       0       0       0
         v_fma_f32      0      1      1      1      1      1       1       1       1       1
     v_fma_mix_f32      0      0      0      1      1      1       1       1       1       1
        v_fmac_f32      0      0      0      1      1      1       1       1       1       1
         v_mac_f32      0      1      1      1      1      1       1       1       1       0
     v_mad_mix_f32      0      0      1      0      0      0       0       0       0       0
       HasMFMA_f64      0      0      0      0      0      1       0       0       0       0
     v_dot4_i32_i8      0      0      0      0      0      0       0       0       0       0
    v_dot4c_i32_i8      0      0      0      0      1      1       0       1       1       1
ArchAccUnifiedRegs      0      0      0      0      0      1       0       0       0       0
    CMPXWritesSGPR      1      1      1      1      1      1       0       0       0       0
          HasAccCD      0      0      0      0      0      1       0       0       0       0
        HasEccHalf      0      0      0      1      1      1       0       0       0       0
         HasWave32      0      0      0      0      0      0       1       1       1       1
     SeparateVscnt      0      0      0      0      0      0       1       1       1       1
  Waitcnt0Disabled      0      0      0      0      1      1       0       0       0       0
# Found  hipcc version 4.3.21300-5bbc51d8
Tensile::WARNING: Global parameter EmbedLibrary = None unrecognised.
# CodeObjectVersion from TensileCreateLibrary: V3
# CxxCompiler       from TensileCreateLibrary: hipcc
# Architecture      from TensileCreateLibrary: gfx906:xnack-
# LibraryFormat     from TensileCreateLibrary: msgpack
sile' 'HIP' '--generate-manifest-and-exit'

################################################################################
# Tensile Create Library
# Detected local GPU with ISA: gfx906
# Detected local GPU with ISA: gfx906

**Comment by ye-luo** [comment] 2021-11-19 01:05
```
yeluo@epyc-server:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           62Gi        38Gi       2.5Gi        37Mi        21Gi        23Gi
Swap:          15Gi       836Mi        15Gi
yeluo@epyc-server:~$ rocm_agent_enumerator
gfx000
gfx906
yeluo@epyc-server:~/opt/rocBLAS$ VERBOSE=1 ./install.sh -d -agfx906:xnack- 2>&1 | tee install.txt
```
here is the output [install.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/7566995/install.txt)
It doesn't seem like OOM issue but more of python module failure due to search paths.

**Comment by zaliu** [comment] 2021-11-19 06:13
@ye-luo I see in your install.out that hipcc was never found.  Where is your hipcc installed?  The default is /opt/rocm/bin/hipcc.

**Comment by zaliu** [comment] 2021-11-23 23:28
@ye-luo Please follow-up or close the issue if resolved.  Thanks.

**Comment by ye-luo** [comment] 2021-11-25 04:35
@zaliu I don't get what you mean "hipcc was never found". My install.txt clearly mentions
```
-- The CXX compiler identification is Clang 13.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm/bin/hipcc - skipped
...
-- The C compiler identification is Clang 13.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rocm/bin/hipcc - skipped
```
This clearly indicates hipcc was found and was being used as both C++ and C compiler.

**Comment by zaliu** [comment] 2021-11-25 05:17
My run shows:

```
-- The CXX compiler identification is Clang 13.0.0
-- Check for working CXX compiler: /opt/rocm/bin/hipcc
-- Check for working CXX compiler: /opt/rocm/bin/hipcc -- works
```
Your run shows
```
-- The CXX compiler identification is Clang 13.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm/bin/hipcc - skipped
```
I'm not sure why your run showed **skipped** while mine showed **works**.  I agree that obviously cmake saw hipcc, but something isn't quite right when cmake checked for a working CXX compiler.

So far we are unable to reproduce your build failure.  We need more information.

Would you please attach /home/yeluo/opt/rocBLAS/build/release/CMakeFiles/CMakeOutput.log?  Thanks.

**Comment by ye-luo** [comment] 2021-11-25 05:31
You misunderstood CMake. "skipped" means CMake is confident that there is no check needed. CMake only checks the compiler when it doesn't have enough confidence in it.
By the way, I'm using CMake 3.20.2.
[CMakeOutput.log](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/7600427/CMakeOutput.log)

**Comment by zaliu** [comment] 2021-11-25 05:48
@sdquiring would you please help with this issue?  What could have caused the error:
```
Traceback (most recent call last):
  File "/home/yeluo/opt/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 25, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile.TensileCreateLibrary'
```

Thanks so much.

**Comment by zaliu** [comment] 2021-11-25 05:52
@ye-luo I tried cmake 3.20.6 and my rocBLAS build worked fine.

**Comment by TorreZuk** [comment] 2021-11-25 17:04
If you later jump to cmake version 3.21+ you should use cmake 3.21.3 version or later as there are unrelated cmake issues with 3.21.x with x < 3.
One closed issue was https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/1196 
I guess we need to find out how cmake 3.20.2 is interfering with the tensile python build (by reproducing) and then potentially blacklist that cmake version for building rocblas.  
Note the error itself seems to be a python import error reported by cmake but not a cmake error, but maybe it is caused by cmake creating an unstable python environment?

**Comment by ye-luo** [comment] 2021-11-25 18:22
Unfortunately 3.21.4 doesn't help. I also think the earlier failure before the python import was the root cause. I have to take a more close look at what actually CMake was doing.

**Comment by TorreZuk** [comment] 2021-11-25 18:39
So does 3.21.4 fail the same way, can you attach a failed log?   If you can help dig deeper add a --trace to the cmake invocation (right after ${cmake_executable} ) in install.sh and save all the build output that will give us full information on what cmake is doing, as your attached log CMakeOutput.log I didn't see a cmake error.   
I'll install 3.21.4 now and try and reproduce as well as so far it doesn't fail for me.  Can you also report 'python3 --version' output?

**Comment by rkamd** [comment] 2021-12-02 00:52
@ye-luo , 
Please provide us the output of the following,
1. `cat /home/yeluo/opt/rocBLAS/build/release/virtualenv/pyvenv.cfg`
2. List of packages visible to the virtual environment , type the following command
    - `source /home/yeluo/opt/rocBLAS/build/release/virtualenv/bin/activate`
    - `pip list >& venv_pip_list.txt`

**Comment by TorreZuk** [comment] 2022-02-04 23:07
It has been two months so assuming this has been resolved or no longer relevant.  Closing the issue.

**Closed by TorreZuk** 2022-02-04 23:07 UTC

**Comment by jbaileyhandle** [comment] 2023-02-26 23:02
@ye-luo Were you ever able to resolve this? I'm having the same issue.

**Comment by ye-luo** [comment] 2023-02-26 23:34
> @ye-luo Were you ever able to resolve this? I'm having the same issue.

I didn't try it any further. You'd better open a new issue against the current code if you are seeking help.

**Comment by TorreZuk** [comment] 2023-02-27 16:07
@jbaileyhandle yes open a new issue and attach any  build logs if you want help.  More recent version of install.sh added --upgrade_tensile_venv_pip flag if pip is also the source of your problem but best to just open new issue with logs and OS details as mentioned in the template and we can advise correctly.  thanks.
